sudo: required

services:
    - docker
    
language: bash

script:
    # Set repo to push to
    - export REPO=tommye123/private-internet-access-docker
    # Prepare qemu
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    # Build image
    - docker build -t $REPO:armhf-latest -f dockerfile-armhf .

after_success:
    # Check the branch is Master and its also not a PR causing a build
    - if [[ $TRAVIS_BRANCH = "master" ]] && [[ $TRAVIS_PULL_REQUEST = "false" ]] ; then
      # Login and push image to Docker
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      # docker tag $REPO $REPO:armhf-latest
      docker push $REPO:armhf-latest
      # docker push $REPO
      fi

# Previous code
# language: generic
# services:
#   - docker
# install:
#   - docker build .
# after_script:
#   - "curl -X POST https://hooks.microbadger.com/images/qmcgaw/private-internet-access/tQFy7AxtSUNANPe6aoVChYdsI_I="
